site_name: Debian FIPS Security Dashboard
site_description: High-Assurance Cryptographic and Compliance Dashboard for Hardened Debian 13 FIPS
site_author: Taha Samy
repo_name: atat69919-hub/debian_fips
repo_url: https://github.com/atat69919-hub/debian_fips

theme:
  name: material
  icon:
    logo: material/shield-check
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - macros:
      module_name: main

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - def_list

nav:
  - Home: index.md
  - Security Validation:
      - Validation Overview: validation/index.md
      - Trivy Vulnerability Scan: validation/trivy.md
      - OpenSCAP Compliance Audit: validation/openscap.